### ISSUE TITLE
调用关闭会报No implementation found for void 

### ISSUE THREAD

**Issue by italks** [Deemonser/AndroidSerialPort#4]
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.deemons.serialportlib.SerialPort.close() (tried Java_com_deemons_serialportlib_SerialPort_close and Java_com_deemons_serialportlib_SerialPort_close__)
        at com.deemons.serialportlib.SerialPort.close(Native Method)
        at com.arcsoft.arcfacedemo.activity.ChooseFunctionActivity.openSerial(ChooseFunctionActivity.java:77)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:4809) 
        at android.view.View$PerformClick.run(View.java:20006) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5280) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by hjhcs121** [comment]
在Java_com_deemons_serialportlib_SerialPort_close 函数前添加 extern c
